# Generated by Django 4.2.20 on 2025-03-16 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiasSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=200, unique=True)),
                (
                    "bias_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("far_left", "Far Left"),
                            ("left", "Left"),
                            ("center_left", "Center Left"),
                            ("center", "Center"),
                            ("center_right", "Center Right"),
                            ("right", "Right"),
                            ("far_right", "Far Right"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("reliability_score", models.FloatField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("click", "Click"),
                            ("save", "Save"),
                            ("like", "Like"),
                            ("dislike", "Dislike"),
                            ("share", "Share"),
                        ],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("interests", models.JSONField(default=list)),
                ("preferred_categories", models.JSONField(default=list)),
                ("preferred_sources", models.JSONField(default=list)),
                ("excluded_sources", models.JSONField(default=list)),
                ("preferred_countries", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="bias_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="country",
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="reliability_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="source",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["published_at"], name="news_articl_publish_90ca8c_idx"
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="news.article"
            ),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="userpreference",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user__isnull", False),
                    ("session_id__isnull", False),
                    _connector="OR",
                ),
                name="user_or_session_required",
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["user", "interaction_type"],
                name="news_userin_user_id_e0b5ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["article", "interaction_type"],
                name="news_userin_article_7afa59_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="userinteraction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user__isnull", False),
                    ("session_id__isnull", False),
                    _connector="OR",
                ),
                name="user_interaction_user_or_session_required",
            ),
        ),
    ]
